#!/usr/bin/env bash
# docker compose 에 남아 있는 인프라 컨테이너를 k8s 파드가 같은 이름으로 찾도록, 컨테이너 IP 를 selector 없는 headless Service + Endpoints 로 쓴다.
# 결과: infra-endpoints.yaml (이 디렉터리). 컨테이너를 다시 만들어 IP 가 바뀌면 다시 돌리고 apply 한다(redis-node-* 는 고정 IP 라 안 바뀐다).
# 파드는 도커 브리지 IP 로 가되, 컨테이너가 publish 한 포트만 통과한다(도커 방화벽) — 아래 포트는 전부 publish 돼 있다(kafka 9092, redis-node 6379 포함).
# 컨테이너가 없거나 해당 네트워크에 붙어 있지 않으면 즉시 실패한다(절반만 쓴 파일을 남기지 않는다).
set -euo pipefail

OUT="$(cd "$(dirname "$0")" && pwd)/infra-endpoints.yaml"
NAMESPACE=modu

# name  container  network  port[,port…]
TABLE='
mysql-member            mysql-member            modu-infra                3306
mysql-member-replica    mysql-member-replica    modu-infra                3306
mysql-chat              mysql-chat              modu-infra                3306
mysql-chat-replica      mysql-chat-replica      modu-infra                3306
mysql-push              mysql-push              modu-infra                3306
mysql-push-replica      mysql-push-replica      modu-infra                3306
mysql-profile           mysql-profile           modu-infra                3306
mysql-profile-replica   mysql-profile-replica   modu-infra                3306
mysql-commerce          mysql-commerce          modu-infra                3306
mysql-commerce-replica  mysql-commerce-replica  modu-infra                3306
redis                   redis                   modu-infra                6379
redis-node-1            redis-node-1            modu-data_redis-cluster   6379
redis-node-2            redis-node-2            modu-data_redis-cluster   6379
redis-node-3            redis-node-3            modu-data_redis-cluster   6379
redis-node-4            redis-node-4            modu-data_redis-cluster   6379
redis-node-5            redis-node-5            modu-data_redis-cluster   6379
redis-node-6            redis-node-6            modu-data_redis-cluster   6379
kafka                   kafka                   modu-infra                9092
zookeeper               zookeeper               modu-infra                2181
mongo-01                mongo-01                modu-infra                27017
mongo-02                mongo-02                modu-infra                27017
mongo-03                mongo-03                modu-infra                27017
minio                   minio                   modu-infra                9000
rabbitmq                rabbitmq                modu-infra                5672
pinpoint-collector      pinpoint-collector      pinpoint-docker_pinpoint  9991,9992,9993
'

command -v docker >/dev/null || { echo "docker 가 PATH 에 없다" >&2; exit 1; }

tmp="$(mktemp)"
trap '/bin/rm -f "$tmp"' EXIT

{
  echo "# GENERATED by gen-infra-endpoints.sh at $(date '+%Y-%m-%d %H:%M:%S') — 직접 고치지 말고 스크립트를 다시 돌린다."
  echo "# docker compose 인프라 컨테이너 → headless Service + Endpoints (selector 없음: endpoint controller 가 덮어쓰지 않는다)."
} > "$tmp"

count=0
while read -r name container network ports; do
  [ -z "$name" ] && continue
  if ! docker container inspect "$container" >/dev/null 2>&1; then
    echo "컨테이너가 없다: $container (compose 스택을 먼저 띄울 것)" >&2
    exit 1
  fi
  ip="$(docker container inspect "$container" -f "{{(index .NetworkSettings.Networks \"$network\").IPAddress}}" 2>/dev/null || true)"
  if [ -z "$ip" ] || [ "$ip" = "<no value>" ]; then
    echo "컨테이너 $container 가 네트워크 $network 에 없거나 IP 가 없다" >&2
    exit 1
  fi
  # 포트가 둘 이상이면 k8s 가 포트 이름을 요구한다. 하나면 이름 없이(가이드의 모양 그대로).
  svc_ports="" ep_ports=""
  IFS=',' read -r -a plist <<< "$ports"
  for p in "${plist[@]}"; do
    if [ "${#plist[@]}" -gt 1 ]; then
      svc_ports+="{name: p$p, port: $p, targetPort: $p}, "
      ep_ports+="{name: p$p, port: $p}, "
    else
      svc_ports+="{port: $p, targetPort: $p}, "
      ep_ports+="{port: $p}, "
    fi
  done
  svc_ports="${svc_ports%, }"; ep_ports="${ep_ports%, }"
  cat >> "$tmp" <<EOF
---
# $container ($network) $ip
apiVersion: v1
kind: Service
metadata: {name: $name, namespace: $NAMESPACE}
spec: {clusterIP: None, ports: [$svc_ports]}
---
apiVersion: v1
kind: Endpoints
metadata: {name: $name, namespace: $NAMESPACE}
subsets: [{addresses: [{ip: $ip}], ports: [$ep_ports]}]
EOF
  count=$((count + 1))
done <<< "$TABLE"

/bin/rm -f "$OUT"
cp "$tmp" "$OUT"
echo "wrote $OUT ($count services)"
