#!/usr/bin/env bash
# modu_platform/config-repo 를 config-service 파드가 /config-repo 로 읽도록 ConfigMap 셋으로 바꾼다 → config-repo-configmaps.yaml (이 디렉터리).
# kustomize 는 kustomization 바깥 경로를 읽지 못하므로(configMapGenerator files: ../../../modu_platform/… 불가) 스크립트가 만든다.
# ConfigMap 키에는 / 를 못 쓰므로 디렉터리마다 하나: config-repo-root(application.yml …), config-repo-messenger, config-repo-commerce.
# config-service Deployment(base/platform/config-service.yaml)가 셋을 /config-repo, /config-repo/messenger, /config-repo/commerce 에 마운트한다.
# 비밀값은 전부 {cipher} 로 암호화돼 있어 이 파일은 비밀이 아니다(복호화 키 ENCRYPT_KEY 는 Secret config-service 에만).
# config-repo 를 고친 뒤: 이 스크립트 → kubectl apply -k overlays/dev → kubectl -n modu rollout restart deploy/config-service
# (ConfigMap 볼륨은 kubelet 이 1분 안에 갱신하지만 config-service 는 기동 때 읽은 search-locations 를 다시 스캔하므로 restart 가 확실하다).
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="${CONFIG_REPO:-$HOME/workspace/modu_platform/config-repo}"
OUT="$HERE/config-repo-configmaps.yaml"
NAMESPACE=modu

[ -d "$REPO" ] || { echo "config-repo 가 없다: $REPO (CONFIG_REPO 로 경로를 줄 수 있다)" >&2; exit 1; }
command -v kubectl >/dev/null || { echo "kubectl 이 PATH 에 없다" >&2; exit 1; }

tmp="$(mktemp)"
trap '/bin/rm -f "$tmp"' EXIT

# 디렉터리의 정규 파일만(하위 디렉터리 제외) --from-file 로 넘긴다. 파일이 하나도 없으면 실패.
emit() {
  local cm="$1" dir="$2"
  local args=() f
  for f in "$dir"/*; do
    [ -f "$f" ] && args+=(--from-file="$f")
  done
  [ "${#args[@]}" -gt 0 ] || { echo "$dir 에 파일이 없다" >&2; exit 1; }
  echo "---"
  echo "# $cm ← $dir"
  kubectl create configmap "$cm" -n "$NAMESPACE" "${args[@]}" --dry-run=client -o yaml
}

{
  echo "# GENERATED by gen-config-repo-configmaps.sh at $(date '+%Y-%m-%d %H:%M:%S') from $REPO — 직접 고치지 말고 스크립트를 다시 돌린다."
  echo "# 값은 전부 {cipher} 암호문이라 비밀이 아니다. config-service 가 ENCRYPT_KEY(Secret)로 복호화해 내려준다."
  emit config-repo-root      "$REPO"
  emit config-repo-messenger "$REPO/messenger"
  emit config-repo-commerce  "$REPO/commerce"
} > "$tmp"

# 안전장치: 평문 비밀이 섞여 들어오지 않았는지(비밀값은 모두 {cipher} 여야 한다) 눈에 띄는 키 이름만 거른다.
if grep -Ein '^\s*(password|secret|secret-key|secretKey|private-key|token|uri|key|api-key|client-secret):\s*\S' "$tmp" | grep -v '{cipher}' | grep -q .; then
  echo "경고: {cipher} 가 아닌 비밀값으로 보이는 줄이 있다 — config-repo 를 확인할 것" >&2
  grep -Ein '^\s*(password|secret|secret-key|secretKey|private-key|token|uri|key|api-key|client-secret):\s*\S' "$tmp" | grep -v '{cipher}' >&2 || true
  exit 1
fi

/bin/rm -f "$OUT"
cp "$tmp" "$OUT"
echo "wrote $OUT"
